version: '3.4'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    build:
      context: ..
      dockerfile: docker-tests/Dockerfile.mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: node_backend_exesize_test
    volumes:
      - mysql-db-data:/var/lib/mysql
  tests:
    build:
      context: ..
      dockerfile: docker-tests/Dockerfile
    environment:
      MYSQL_DATABASE_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: node_backend_exesize_test
    depends_on:
      - mysql_db

volumes:
  mysql-db-data:
